name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: "2.2.0"
        channel: "stable"
    - run: flutter pub get
    - run: flutter test
